/* This file was generated by SableCC (http://www.sablecc.org/). */

package mongo.sablecc.node;

import mongo.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TCommentline extends Token
{
    public TCommentline()
    {
        super.setText("//");
    }

    public TCommentline(int line, int pos)
    {
        super.setText("//");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCommentline(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCommentline(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCommentline text.");
    }
}
